enums(
    "TRAIN_INCREMENTAL",
    "TRAIN_BATCH",
    "TRAIN_RPROP",
    "TRAIN_QUICKPROP",
    "TRAIN_SARPROP"
);

enums(
    "LINEAR",
    "THRESHOLD",
    "THRESHOLD_SYMMETRIC",
    "SIGMOID",
    "SIGMOID_STEPWISE",
    "SIGMOID_SYMMETRIC",
    "SIGMOID_SYMMETRIC_STEPWISE",
    "GAUSSIAN",
    "GAUSSIAN_SYMMETRIC",
    "GAUSSIAN_STEPWISE",
    "ELLIOT",
    "ELLIOT_SYMMETRIC",
    "LINEAR_PIECE",
    "LINEAR_PIECE_SYMMETRIC",
    "SIN_SYMMETRIC",
    "COS_SYMMETRIC",
    "SIN",
    "COS"
);

enums(
    "ERRORFUNC_LINEAR",
    "ERRORFUNC_TANH"
);

enums(
    "STOPFUNC_MSE",
    "STOPFUNC_BIT"
);

enums(
    "NETTYPE_LAYER",
    "NETTYPE_SHORTCUT"
);
